### PR TITLE
Strip binary, update to go-1.17.6

### PR DESCRIPTION
**Pull request by majst01**
With this PR the binary is compiled with go 1.17.6 to close some of the open CVE´s in go 1.17.1. 
Furthermore the resulting binary is stripped which reduces the size of the binary by ~10MB.

```
before:
-rwxr-xr-x    1 root     root      32766008 Jan 13 16:07 /bin/headscale

after:
-rwxr-xr-x    1 root     root      22325232 Jan 14 08:14 /bin/headscale
```

- [x] read the [CONTRIBUTING guidelines](README.md#user-content-contributing)
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

**Comment by kradalby** [comment]
The ci jobs also needs to be upgraded and go.mod, would you mind doing that aswell?

Thanks

**Comment by majst01** [comment]
> The ci jobs also needs to be upgraded and go.mod, would you mind doing that aswell?
> 
> Thanks

gimmi a second

**Comment by majst01** [comment]
Why are all integration tests failing ? @kradalby  Have you any clue

**Review by juanfont — APPROVED** [review]

**Comment by juanfont** [comment]
This is great! Thanks :+1:

**Comment by ohdearaugustin** [comment]
Why got the build workflow changed to 1.17, this will destroy reproducible builds. Rather set it explicitly to 1.17.6

**Comment by ohdearaugustin** [comment]
@juanfont @kradalby What is your opinion on that?

**Comment by ohdearaugustin** [comment]
Yeah I will do a PR so set that specifically again.

I was also thinking about something like renovate or dependency bot, as we would also use it for the golang packages and the docker containers. I will also take a look at that and try to test it out in a fork.

**Pull request merged**
