### PR TITLE
arm64 docker image build in release process

### PR DESCRIPTION
**Pull request by fdelucchijr**
Seeing that arm64 builds of CLI are already implemented ( #168 ), this adds arm64 arch digests to the Release image.
Also, I'm adding cache for the build layer to speed up the deployment. 

Loving your work!
Will upload a Helm chart as soon as I understand DERP systems.

### CODE REVIEW

**Comment by ohdearaugustin** [comment]
Looks good so far. Probably should be implemented after #214.

**Comment by ohdearaugustin** [comment]
BTW: I already started creating a helm chart a while ago, but didn't finished it yet. https://github.com/ohdearaugustin/charts/tree/topic/headscale/charts/headscale

**Comment by kradalby** [comment]
Could you resolve the merge conflict? @fdelucchijr 

This looks reasonable to me, @ohdearaugustin @juanfont ?

**Comment by ohdearaugustin** [comment]
Yeah I'm in favor for it. Just needs to be adopted due to the changes of PR #214.

**Comment by fdelucchijr** [comment]
Ready!, I also added cache and platform to the Debug job

**Comment by fdelucchijr** [comment]
> BTW: I already started creating a helm chart a while ago, but didn't finished it yet. https://github.com/ohdearaugustin/charts/tree/topic/headscale/charts/headscale

Ok! I will take a look, I already adapted a little the kustomize files in the /K8s folder in order to set up my own configs. Do you know some good community helm chart repo for this kind of deployment?

**Comment by kradalby** [comment]
Just need to run make fmt and then it should be good

**Review by kradalby — APPROVED** [review]

**Comment by ohdearaugustin** [comment]
@fdelucchijr let's move the discussion about helmchart to #228

**Pull request merged**
