### PR TITLE
Simplify code around latest state change map updates

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Updates `xsync` to v2 and simplifies the code slightly.

- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
The failed build looks unrelated, but I may be wrong.

**Comment by kradalby** [comment]
Yes I’ll fix it and then it should be good Sent from Proton Mail for iOS On Fri, Oct 28, 2022 at 07:43, Andrei Pechkurov ***@***.***> wrote:  
The failed build looks unrelated, but I may be wrong.

**Review by kradalby — DISMISSED** [review]
Great, thanks for taking the time to sort this for us :), build should pass now

edit: I spoke too soon. ☕

**Comment by puzpuzpuz** [comment]
The failed test (`TestPingAllPeersByAddress`) seems to be timing out on `main` as well.

**Comment by puzpuzpuz** [comment]
The failed test (`TestPingAllPeersByAddress`) seems to be timing out on `main` as well.

**Review by kradalby — APPROVED** [review]

**Pull request merged**
