### PR TITLE
Fix IP Address Order Bug

### LINKED ISSUE #1344: Tailscale status strange IP display
**Bug description**

When I run "Tailscale status," some nodes show ipv6 ip, and some nodes show ipv4 ip.

And ipv4 and ipv6 both work on these nodes.

For example, I can use fd7a:115c:a1e0::3 and 100.64.0.3 to connect the 2nd node in the pic, and I can use fd7a:115c:a1e0::c and 100.64.0.12 to connect the 3rd node too.

screenshot

**To Reproduce**

I removed and re-added the nodes, but it still shows the same.

**Context info**

In the screenshot,
1st Ubuntu shows ipv6
2nd Debian shows ipv6
3rd iOS shows ipv4
4th Android shows ipv4
5th Windows shows ipv4
6th iOS shows ipv6
7th macOS show sipv6

Out the screenshot,
9th Windows shows ipv6

That is so strange.

### PR DESCRIPTION
**Pull request by qzydustin**
- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [x] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

Fixes #1344

Apologies for the previous pull request containing errors. I have now made the necessary revisions.

### CODE REVIEW

**Comment by juanfont** [comment]
Thanks for the PR! Can you add a couple of unit tests?

**Comment by qzydustin** [comment]
I have errors of format.

> Error: return with no blank line before (nlreturn)

In the if branch, I only have one line code. Should add a blank line before?

> Error: parameter name 'i' is too short for the scope of its usage (varnamelen)

The parameter i is the index1. Should I change it?

**Comment by qzydustin** [comment]
Unit tests added.

**Comment by qzydustin** [comment]
Is there anything that I need to do?

**Comment by kradalby** [comment]
This needs to be rebased, the code is currently frozen as we are restructuring it, if it's rebased, we can let this one in.

**Comment by qzydustin** [comment]
Completed based on the latest code re-modification

**Review by kradalby — APPROVED** [review]

**Pull request merged**
