### PR TITLE
document running exit nodes

### PR DESCRIPTION
**Pull request by mpldr**
Currently the only kind-of documentation is #210 which is outdated. To remedy this, add a document describing the process.

- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [x] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

**Review by juanfont — COMMENTED** [review]
Thanks for the contribution!!

Would it be possible to remove the references to docker compose? Just to make it more agnostic...

**Comment by mpldr** [comment]
Done :)

**Review by juanfont — APPROVED** [review]
Great thanks!!

**Review by juanfont — APPROVED** [review]

**Comment by juanfont** [comment]
Thanks!

**Pull request merged**
