### PR TITLE
#2176 Manual approval of the node

### LINKED ISSUE #2176: [Feature] Manual approval of the node
### Use case

It is necessary to control the nodes connecting to my network.

### Description

For example: registering a new node via CLI requires an explicit action by the administrator, which reduces the risk of unauthorised access to the network, unlike registering a node via OIDC, where all responsibility falls on an external OIDC system that can be compromised. To reduce the risk, additional approval (Device approval - https://tailscale.com/kb/1099/device-approval) is required for new nodes on the network.

### Contribution

- [X] I can write the design doc for this feature
- [X] I can contribute this feature

### How can it be implemented?

- Add an additional field `authorised: datetime IS NULL` to the nodes table database. 
- Add `IsAuthorised` validation methods to the Node model that will check that the field is not NULL or IsZero.
- Replace `MachineAuthorised: !node.IsExpired()` with `MachineAuthorized: node.IsAuthorized()`.
- Add an additional CLI command to approve a node
- Add forced approval of a node if it is registered via CLI
- Add additional keys to PreAuthKey to register immediately approved node
- Introduce an additional check in the `CanAccess` method to block approved nodes from communicating with unapproved nodes

P.S. I'm already using this change on my network.

### PR DESCRIPTION
**Pull request by hopleus**
- [x] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [x] added unit tests
- [x] added integration tests
- [x] updated documentation if needed
- [x] updated CHANGELOG.md

Fixes #2176

### CODE REVIEW

**Comment by hopleus** [comment]
> I will get back to this after 0.24.0 is released. Can you rebase it so it is a bit easier to review and it doesnt contain all the other commits from main?

>> it doesnt contain all the other commits from main?
I'll do it

>> rebase it so it is a bit easier to review
What do you mean by "easier to review"?

**Comment by kradalby** [comment]
> What do you mean by "easier to review"?

Just the rebase, at the moment the branch/PR contains 56 commits, but it looks like max half are related to the changes. if related ones can also be squashed up, that might help too.

**Comment by hopleus** [comment]
> > What do you mean by "easier to review"?
> 
> Just the rebase, at the moment the branch/PR contains 56 commits, but it looks like max half are related to the changes. if related ones can also be squashed up, that might help too.

I'll do it in a new PR then, I'll close this one.

**Comment by panda2134** [comment]
@hopleus Hi, may I ask where can I find the new PR?

**Pull request closed without merging**
