### PR TITLE
Fix #1601 - Group examples need group: prefix

### LINKED ISSUE #1601: ACL Documentation error
On this page: https://headscale.net/acls/#acl-setup

The very bottom provides these examples:

```
    // We still have to allow internal users communications since nothing guarantees that each user have
    // their own users.
    { "action": "accept", "src": ["boss"], "dst": ["boss:*"] },
    { "action": "accept", "src": ["dev1"], "dst": ["dev1:*"] },
    { "action": "accept", "src": ["dev2"], "dst": ["dev2:*"] },
    { "action": "accept", "src": ["admin1"], "dst": ["admin1:*"] },
    { "action": "accept", "src": ["intern1"], "dst": ["intern1:*"] }
```

This doesn't work. The correct syntax has group: in front, for example:
```
    { "action": "accept", "src": ["group:boss"], "dst": ["group:boss:*"] },
```

### PR DESCRIPTION
**Pull request by Sh4d**
- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [x] updated documentation if needed
- [ ] updated CHANGELOG.md

This is a minor tweak for https://github.com/juanfont/headscale/issues/1601

### CODE REVIEW

**Comment by amefs** [comment]
A predefined single-user group is still required in the `groups` section as a workaround, Unless Headscale implements `autogroup:self` `autogroup:members`.
```
"group:boss": ["boss"],
"group:dev1": ["dev1"],
"group:dev2": ["dev2"],
```

**Comment by Sh4d** [comment]
> A predefined single-user group is still required in the `groups` section as a workaround, Unless Headscale implements `autogroup:self` `autogroup:members`.
> 
> ```
> "group:boss": ["boss"],
> "group:dev1": ["dev1"],
> "group:dev2": ["dev2"],
> ```

Sorry I don't understand what you're talking about. Workaround for what? This is just a doc fix to make the example at the bottom actually work. The current code would only work if those groups were hostnames, groups need the group: prefix.

Headscale has no autogroup support AFAIK.

**Comment by amefs** [comment]
The `dev1` and `dev2` are defined in the same group `group:dev`, you will find `WRN No IPs found with the alias group:dev1`.

**Comment by Sh4d** [comment]
> The `dev1` and `dev2` are defined in the same group `group:dev`, you will find `WRN No IPs found with the alias group:dev1`. We need to define groups for each user, to make sure isolated from other users here.

Ahh I see now, thanks. I misinterpreted what it was trying to do (specify the users rather than the groups). I think my PR is completely wrong =)

**Pull request closed without merging**
