### PR TITLE
Env config

### LINKED ISSUE #674: Env var for config location
**Feature request**

I'm currently running headscale in Docker and have placed the config in `/var/lib/headscale/` for the sake of convenience (then I only need one Docker volume). Sadly, this makes using the CLI very inconvenient in turn as I have to specify the config location each time.

As a simple solution, I think it would be great to be able to specify the config location via env var.

### PR DESCRIPTION
**Pull request by huskyii**
- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [x] added integration tests
- [ ] updated documentation if needed
- [x] updated CHANGELOG.md

Fixes #674

### CODE REVIEW

**Comment by huskyii** [comment]
@juanfont rebased to latest main branch and integration test failures resolved

**Comment by kradalby** [comment]
0.16.4 has been released so we need to move it to 0.17.0, if you do that, then happy to merge

**Comment by huskyii** [comment]
> 0.16.4 has been released so we need to move it to 0.17.0, if you do that, then happy to merge

sure, updated.

**Review by kradalby — APPROVED** [review]

**Comment by juanfont** [comment]
thanks!!

**Pull request merged**
