### PR TITLE
Added info about custom URL feature break.

### PR DESCRIPTION
**Pull request by rbangert**
- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [x] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

**Comment by juanfont** [comment]
@rbangert have you consider opening an issue in https://github.com/tailscale/tailscale

**Comment by rbangert** [comment]
I have created one with them, and dug through the code to find where it broke.
 [https://github.com/tailscale/tailscale/issues/6671](tailscale/#6671)

I suspect it will be a bit before this gets addressed, and thought this might be a good idea for the time being after seeing a few people come into discord over it yesterday and learning the windows client had also been impacted.

**Comment by kradalby** [comment]
This is not correct for the Windows client, the method for logging in has changed and is docs are located on your running instance under yourheadscaledomain.com/windows.

The incorrect windows document will be removed in #1066

**Review by rbangert — COMMENTED** [review]
Updated windows doc with the instructions from /templates & reverted changes to README.md regarding the Windows Client.

**Pull request closed without merging**
