### PR TITLE
PollNetMapStream: do not create any rows during long-poll operation

### LINKED ISSUE #232: Deleted node is back online
Running a test network with 4 nodes on headscale v0.11.0.

On the headscale server, I tried to remove a currently active node. I want to block/delete it from the network.

List nodes:
```bash
headscale -n net1 nodes list
ID | Name     | NodeKey | Namespace | IP address | Ephemeral | Last seen           | Online
1  | laptop   | [XX]    | net1      | 100.64.0.1 | false     | 2021-11-21 13:01:42 | true  
2  | test-2   | [YY]    | net1      | 100.64.0.2 | false     | 2021-11-21 13:01:16 | true  
3  | test-1   | [ZZ]    | net1      | 100.64.0.3 | false     | 2021-11-21 13:01:10 | true  
4  | bullseye | [AA]    | net1      | 100.64.0.4 | false     | 2021-11-21 13:01:35 | true 
```
Delete node
```bash
headscale -n net1 nodes delete 4
Do you want to remove the node bullseye? Yes
Node deleted
```
After deletion:

```bash
$ headscale -n net1 nodes list
ID | Name   | NodeKey | Namespace | IP address | Ephemeral | Last seen           | Online
1  | laptop | [XX]    | net1      | 100.64.0.1 | false     | 2021-11-21 13:04:42 | true  
2  | test-2 | [YY]    | net1      | 100.64.0.2 | false     | 2021-11-21 13:04:16 | true  
3  | test-1 | [ZZ]    | net1      | 100.64.0.3 | false     | 2021-11-21 13:05:10 | true  
```
Just a short time later, without touching any of the nodes or connections

```bash
$ headscale -n net1 nodes list
ID | Name     | NodeKey | Namespace | IP address | Ephemeral | Last seen           | Online
1  | laptop   | [XX]    | net1      | 100.64.0.1 | false     | 2021-11-21 13:06:42 | true  
2  | test-2   | [YY]    | net1      | 100.64.0.2 | false     | 2021-11-21 13:06:16 | true  
3  | test-1   | [ZZ]    | net1      | 100.64.0.3 | false     | 2021-11-21 13:07:10 | true  
4  | bullseye | [AA]    | net1      | 100.64.0.4 | false     | 2021-11-21 13:06:37 | true 
```

Logs
```
2021-11-21T13:05:17Z ERR Cannot update machine from database error="record not found" channel=Done handler=PollNetMapStream machine=bullseye
2021-11-21T13:05:17Z WRN Ignoring request, cannot find machine with key e64efccaa9e6f4b59f77c3345a1c38ac518b46712f1086f59e96672515a4be0f handler=PollNetMap
[GIN] 2021/11/21 - 13:05:17 | 401 |      376.24µs |    11.22.33.44 | POST     "/machine/e64efccaa9e6f4b59f77c3345a1c38ac518b46712f1086f59e96672515a4be0f/map"
[GIN] 2021/11/21 - 13:05:17 | 200 |         9m19s |    11.22.33.44 | POST     "/machine/e64efccaa9e6f4b59f77c3345a1c38ac518b46712f1086f59e96672515a4be0f/map"
2021-11-21T13:05:18Z INF Client is ready to access the tailnet handler=PollNetMap machine=bullseye
2021-11-21T13:05:18Z INF Sending initial map handler=PollNetMap machine=bullseye
2021-11-21T13:05:18Z INF Notifying peers handler=PollNetMap machine=bullseye
```

How do I block a node from my network without touching the node itself?

Please bear with me, its the first time I play with headscale - maybe missed something.

### PR DESCRIPTION
**Pull request by enoperm**
- [x] read the [CONTRIBUTING guidelines](README.md#user-content-contributing)
- ~~raised a GitHub issue or discussed it on the projects chat beforehand~~ - found existing issues.
- ~~added unit tests~~ - testing requires a client, currently only available in integration tests.
- ~~] added integration tests~~
- updated documentation if ~~needed~~ - PR contains changes without changes to expected behaviour towards clients or users.
- [x] updated CHANGELOG.md

Fixes #232 (manually tested in the no-preauthkeys case)
Related to #93

### CODE REVIEW

**Comment by juanfont** [comment]
This looks good to me. @kradalby what is your opinion?

**Comment by kradalby** [comment]
Yep I'm happy to have this, @enoperm do you think it is suitable for merge?

**Comment by enoperm** [comment]
Sorry, haven't had the time to finish up the MR the way I wanted last week. That said, I *have* thought a bit about it, and ultimately decided I'd rather not add a deployment test for this specific issue unless requested - the original problem looks implementation specific, and unlikely to re-emerge in the future, so long as GORM or `${insert future data storage layer}` is used as intended. It sounds a bit like a waste to prolong every CI run by minutes for it.

The changes are not so large that I see it as a requirement of not breaking things, either.

**Comment by enoperm** [comment]
I seem to have messed up a bit when I first tried to merge the current `main`. so ended up rebase-ing and force pushing. I kindly request a re-review so as to make sure nothing weird happened that I have not noticed, but other than that, it should be okay.

**Review by kradalby — DISMISSED** [review]

**Comment by kradalby** [comment]
@enoperm Do you mind fixing the `prettier` lint? I have a PR open to sort the golangci one, so you can ignore that for now.

**Review by kradalby — APPROVED** [review]

**Pull request merged**
