### PR TITLE
build docker images on PR

### PR DESCRIPTION
**Pull request by kradalby**
Take 2, not from fork, supersedes #2053

Sometimes we want people to test features in PRs and
not everyone is used to using git, build go and docker.

This commit builds docker containers and pushes them to
GHCR (not dockerhub) for testing on pushes to branches
that has open pull requests to main using Ko.
This is configured to mimic the debug images produced
by goreleaser.

### CODE REVIEW

**Comment by kradalby** [comment]
Looks like this isnt possible,

`pull_request` does not have secrets access, so cannot push.

`pull_request_target` has secret access, but runs on the base branch, not the new commits, so the changes would not be reflected.

**Comment by chriswiggins** [comment]
@kradalby this should work, You need to make sure that the permissions are set for the `GITHUB_TOKEN` so that it is allowed to write to the package registry:

```yaml
permissions:
  pull-requests: write
  packages: write
```

You also need to authenticate to the registry first:
```yaml
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by masterwishx** [comment]
> Collaborator
> ###

last beta4 builded `...beta.4` instead of `...beta4`

**Comment by kradalby** [comment]
@masterwishx this is in response to https://github.com/juanfont/headscale/issues/1923

**Comment by kradalby** [comment]
@chriswiggins, I think I could not get it to work for PRs at all? and from what I read in the gh docs secrets are not available, but I might have the motivation to fight and try this again at another time...

**Comment by kradalby** [comment]
@masterwishx oh dear, I'll post it to the #1923 issue.

**Pull request closed without merging**
