### PR TITLE
Remove dockerfile bloat

### LINKED ISSUE #2220: Debug docker image size is ridiculous.
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The new "unofficial" image is 2.5 gigabytes due to non-standard approaches in "Dockerfile.debug"

### Expected Behavior

Just do normal docker best-practices.

### Steps To Reproduce

Build your dockerfile, its huge.

### Environment

```markdown
Debian Bookworm,
.23
NA
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sevenrats**
- [x] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [x] updated CHANGELOG.md

### CODE REVIEW

**Comment by sevenrats** [comment]
related to #1716

**Comment by kradalby** [comment]
This dockerfile is only used in integration tests, it is using Debian and is «intentionally» bloated.

**Comment by sevenrats** [comment]
k. this is feeling more like a downstream. thanks for your consideration.

**Comment by kradalby** [comment]
The file should be renamed as it is not part of the debug build, its kind of confusing

**Comment by sevenrats** [comment]
honestly its nbd. adding a third dockerfile won't improve the UX imho and due to the `COPY . .` which causes any change to the top level folder to redo the go build layer, which is very inefficient. it will be much easier to third-party this because I can then pull the repo in and copy it as a subdir.  this in turn will allow me to easily support many different build flavors without disrupting your build process. headscale will still get these benefits we will just keep it downstream.

**Pull request closed without merging**
