### PR TITLE
Fix errror in kustomize init.bash

### PR DESCRIPTION
**Pull request by leigh-johnson**
- [x] read the [CONTRIBUTING guidelines](README.md#user-content-contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [] added unit tests (N/A)
- [] added integration tests (N/A)
- [] updated documentation if needed (N/A)
- [] updated CHANGELOG.md (N/A)

* Fixes issue 318.1 reported in #318
* shellcheck linter (shellcheck defaults)
* Added check for `wg` and print version for future debugging/issue reporting quality of life :raised_hands:

### CODE REVIEW

**Comment by ohdearaugustin** [comment]
Is the configuration working with only random data for the derp?

**Comment by leigh-johnson** [comment]
> Is the configuration working with only random data for the derp?

No, the demo values would need to be replaced with custom DERP servers. https://tailscale.com/kb/1118/custom-derp-servers/

Not sure what the maintenance goals are for this demo, but happy to lend a hand if this is helpful. Otherwise, no worries about closing this PR. After running through the demo, I created my own deployment templates to support a different Ingress and external Postgres host.

**Comment by ohdearaugustin** [comment]
As by now the kustuomize templates are not really maintained by anyone. And the general idea was to move to a helm chart. See #228. Just didn't managed to have time for it. We also were thinking about removing this configuration.

I would not prefer to add configuration that is not "working" too.

Maybe you could add some comment to the other issue for what the helm chart should be supporting.

**Comment by leigh-johnson** [comment]
> As by now the kustuomize templates are not really maintained by anyone. And the general idea was to move to a helm chart. See #228. Just didn't managed to have time for it. We also were thinking about removing this configuration.
> 
> I would not prefer to add configuration that is not "working" too.
> 
> Maybe you could add some comment to the other issue for what the helm chart should be supporting.

Sounds good, thanks for the link to that issue about helm! 

What do you think of adding a more explicit deprecation notice here? The recent-ish commit plus note about being community-maintained is what made me contribute this patch, which just gets the end-to-end demo working without errors.
https://github.com/juanfont/headscale/tree/main/docs/examples/kustomize

**Pull request closed without merging**
