### PR TITLE
Adjust template for OIDC callback page (from #1435)

### PR DESCRIPTION
**Pull request by vsychov**
Hello,

This pull request enhances the user-friendliness of the OIDC callback page, as per the disagreement on relocating it to the config file as discussed in issue #1435.

- [x] The [CONTRIBUTING guidelines](README.md#contributing) have been thoroughly read and understood.
- [x] CHANGELOG.md has been updated.

### CODE REVIEW

**Comment by vsychov** [comment]
Hello @juanfont, I hope this submission meets your approval for merging.

**Comment by kradalby** [comment]
@vsychov there is a couple of linter issues, would you mind fixing them?

**Comment by vsychov** [comment]
@juanfont , fixed

**Comment by vsychov** [comment]
@juanfont , all checks passed, maybe it can be merged?

**Review by kradalby — APPROVED** [review]

**Pull request merged**
