### PR TITLE
Optimize getFilteredByACLPeers

### PR DESCRIPTION
**Pull request by QZAiXH**
- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

Use map to speed up lookups. This can effectively reduce cpu usage

### CODE REVIEW

**Comment by QZAiXH** [comment]
@juanfont Please take a look at this pr

**Comment by kradalby** [comment]
I allowed the tests to run, we will need a bit more time to review this one to make sure we understand the changes.

**Comment by QZAiXH** [comment]
@kradalby Having trouble running TestPingAllByIP, where can I see the acl file and which user the node belongs to when testing?

**Comment by kradalby** [comment]
@QZAiXH, good work, I have picked up your changes in #1254, will get @juanfont to review.

**Pull request closed without merging**
