### PR TITLE
Update document about reverse-proxy

### PR DESCRIPTION
**Pull request by kevin1sMe**
- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [x] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

**Comment by kevin1sMe** [comment]
issue #851

**Comment by juanfont** [comment]
@kevin1sMe can you run prettier? There is something off in the md...

**Comment by kevin1sMe** [comment]
> @kevin1sMe can you run prettier? There is something off in the md...

I'm sorry, I have do prettier now. Is anything else I can do?

**Review by juanfont — APPROVED** [review]
Great! Thanks!

**Pull request merged**
