### PR TITLE
Custom machine address

### PR DESCRIPTION
**Pull request by lembq**
We wanted to assign a custom ip address to our machines on the tailscale network. After a quick google search we found a the request for this enhancement (#1455 ). I implemented the functionality to be able to assign a specific IPv4 address when registering a machine. There is a new flag called --ip which can be set optionally. An example can be seen in the documentation. Without setting this flag the registration will work the same way as previously (the sequentially next ip will be assigned). An already used ip cannot be choosen. An ip address that is outside the configured prefix range is also not possible. 

I tested this new feature locally with docker and one node but I will also test it on a larger scale in the next few days.

No OIDC and IPv6 support yet to keep the changes as small as possible.

The outcommented part in machine.go is just one way of assigning an IPv6 address as well. I did not find it sophisticated enough to use so I only support IPv4 yet. I would appreciate any ideas on how I could make that part robust because this design decision is crucial for the future developement. 

I welcome any feedback or suggestions from the community and fellow contributors. Your opinions and insights are greatly appreciated as I strive to improve and learn.

- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [x] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

**Comment by kradalby** [comment]
Hi! as part of #1473, we have reorganised a lot of the code. 

To clear PRs that needs to be rebased or redone, we are closing open PRs that will require significant code change to be merged.

In addition, the issue of the PR might in some cases have been fixed, change or no longer relevant, so it would be great if this is considered as well.

Thank you for your contribution! 

If it is still relevant and the PR is reopened, we will aim at getting the changes into the next release after the reorg if accepted.

**Comment by Kayakflo** [comment]
@lembq Do you consider reopening the PR after merging the changes made in #1473 ? 
It would be highly appreciated 🙏

**Comment by kradalby** [comment]
While this was closed with a standardised message, I do not believe we will accept this feature for the time being, it does require more thought than it might seem on the surface and we are currently not willing to open this can of worms.

**Comment by lembq** [comment]
I am eager and fully committed to contributing to this project by working on this pull request. I hope i can get the opportunity to implement this funcionality in a robust way after the merge. I can also come up with new ideas to make the implementation of this functionality clean and simple.

**Pull request closed without merging**
