### PR TITLE
Added version checker on Headscale startup

### PR DESCRIPTION
**Pull request by juanfont**
This small PR just adds an updated version checker on startup. 

It uses https://github.com/tcnksm/go-latest to fetch the latest release in GitHub.

### CODE REVIEW

**Review by kradalby — APPROVED** [review]

**Comment by qbit** [comment]
Would it be possible to add a config option to disable this? At least in OpenBSD ports land it's typical that these kind of checks are disabled so as not to cause confusion for people that installed it via `pkg_add`.

The alternative would be that I have to carry patches in the OpenBSD port to disable the check.

**Review by kradalby — CHANGES_REQUESTED** [review]
Actually @qbit has a good point.

Also having something call the internet is not optimal without being able to disable it.

How does that library handle lack of internet?

**Comment by juanfont** [comment]
@qbit @kradalby indeed, that's hell of a point. Would make sense to limit the checks to `runtime.GOOS == "linux"` and  `runtime.GOOS == "darwin"` (the OS that we have binaries for) ?

**Comment by qbit** [comment]
That makes sense to me, I do still think it would be good to have an option to completely disable it for people that don't want to tell github what software they are running.

**Comment by kradalby** [comment]
> @qbit @kradalby indeed, that's hell of a point. Would make sense to limit the checks to `runtime.GOOS == "linux"` and  `runtime.GOOS == "darwin"` (the OS that we have binaries for) ?

No OS checks, those operating systems also have package managers.

It should be possible to turn off for all package maintainers

**Comment by juanfont** [comment]
> This small PR 

Famous last words 😂😂

Indeed, those OS might end up having Headscale packages. We leave it then as a viper config setting (via the `config.json` or ENV) ?

**Comment by qbit** [comment]
LGTM!

**Review by kradalby — APPROVED** [review]

**Pull request merged**
