### PR TITLE
Fix/improve documentation formatting

### PR DESCRIPTION
**Pull request by majabojarska**
## Description

Fixes markdown formatting/indentation issues to properly render via mkdocs:
  - Enumeration. Several enumerated lists rendered improperly, as multiple "1." entries:
    image
  - Replace sequential enumeration (`1. 2. 3. ...`) with `1.`-based enumeration. The renderer takes care of mapping the correct index to each list element. Generally easier to maintain.
  - Improves readability by using admonitions, e.g.:
    image
  - Improves consistency of `monospace` formatting for package/image names.

## Validation steps

1. Run `mkdocs serve`.
2. Open the live preview.
3. Inspect the rendered documents relevant to the PR's scope.

---

- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [ ] ~raised a GitHub issue or discussed it on the projects chat beforehand~ Not applicable
- [ ] ~added unit tests~ Not applicable
- [ ] ~added integration tests~ Not applicable
- [x] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

**Review by Orhideous — APPROVED** [review]

**Comment by Orhideous** [comment]
https://github.com/juanfont/headscale/pull/1659 may cause potential merge conflict.

**Comment by majabojarska** [comment]
I've refreshed the whole thing, rebased and resolved conflicts.

**Comment by kradalby** [comment]
@ohdearaugustin could you have a look?

**Review by ohdearaugustin — COMMENTED** [review]
We just need to run prettier again

**Comment by ohdearaugustin** [comment]
It seems like that prettier will break most of the changes again.

**Comment by ohdearaugustin** [comment]
So I tried now several things that prettier won't destroy the indentation of the code-block in a list, but it seems like nothing works.

Even an ignore block like:
~~~
   <!-- prettier-ignore-start -->
   ```shell
   mkdir -p ./headscale/config
   cd ./headscale
  ```
   <!-- prettier-ignore-end -->
~~~

My assumption is that mkdocs and prettier use different markdown libraries with different standards for code blocks in lists. I really thinking to add those files just to the ignore list to get it fixed.

**Review by ohdearaugustin — APPROVED** [review]
Will merge when #1832 is fixed, then the docu should also be correctly deployed again.

**Review by Orhideous — APPROVED** [review]

**Pull request merged**
