### PR TITLE
fix bug in #912

### PR DESCRIPTION
**Pull request by CNLHC**
- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

### CODE REVIEW

**Comment by CNLHC** [comment]
Oh the test broken
I will try to solve the problem

**Comment by kradalby** [comment]
I think this fails the tests because it changes how the ID is put into the cache for only one registration method, I think we should probably not change that, or normalise it so it is _always_ one thing for all methods. 

I notice that there was another fix submitted, but then withdrawn which might be related to a patch I did a while ago: https://github.com/juanfont/headscale/pull/918

I am happy with one of the following solutions:

- The ID used in reg url and the cache does _always_ contain `nodekey:`
- It _never_ contains `nodekey:`

**Comment by CNLHC** [comment]
> I think this fails the tests because it changes how the ID is put into the cache for only one registration method, I think we should probably not change that, or normalise it so it is _always_ one thing for all methods.
> 
> I notice that there was another fix submitted, but then withdrawn which might be related to a patch I did a while ago: #918
> 
> I am happy with one of the following solutions:
> 
> * The ID used in reg url and the cache does _always_ contain `nodekey:`
> * It _never_ contains `nodekey:`

Thanks for your suggestion。

I have already made the test pass locally by prefixing everything with a `nodekey`, but I am not sure which style is preferred.

Actually, I am asking this question on the discord just before 3 minutes you post a comment here 😆

**Comment by CNLHC** [comment]
I think there still remains one test to fix : `test_integration_v2_general`

**Comment by kradalby** [comment]
@juanfont has some work on integration testing this, and he will test this branch with his work in #929 before we proceed.

**Review by kradalby — APPROVED** [review]

**Pull request merged**
