### PR TITLE
remove gin completely, ~2MB reduction on final binary

### PR DESCRIPTION
**Pull request by huskyii**
- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [x] updated CHANGELOG.md

### CODE REVIEW

**Comment by huskyii** [comment]
@kradalby hi, as this PR changes go.sum/go.mod, vendorSha256 in flake.nix line 27 needs to be updated, how to compute the sha256?

**Comment by restanrm** [comment]
> @kradalby hi, as this PR changes go.sum/go.mod, vendorSha256 in flake.nix line 27 needs to be updated, how to compute the sha256?

I think you just have to run it locally and it will print the sha256 in your terminal or in the github actions fail log.

**Comment by kradalby** [comment]
You can either run nix build locally or check the failed the build:

https://github.com/juanfont/headscale/runs/7362820827?check_suite_focus=true#step:5:183

**Comment by huskyii** [comment]
@restanrm @kradalby 

Main workstation runs OpenBSD, do not have access to nix.
Check GitHub Action's build log works, thx~

**Review by kradalby — APPROVED** [review]

**Pull request merged**
