### PR TITLE
Add -race Flag to GitHub Action and Fix Data Race in CreateTailscaleNodesInUser

### PR DESCRIPTION
**Pull request by nadongjun**
- [x] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

- This PR adds the -race flag to both unit and integration tests and addresses data race issues in the CreateTailscaleNodesInUser method.

The changes include:

- Added -race flag: Included the -race flag in both test and test_integration targets in the Makefile to enable race condition detection for unit and integration tests. Github action is also configured to detect data races.
- Fixed data race in CreateTailscaleNodesInUser: Updated the CreateTailscaleNodesInUser method to resolve data race issues related to concurrent access.

### Log
```
WARNING: DATA RACE
Read at 0x00c000356030 by goroutine 106:
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser.func1()
      /Users/dongjunna/br/headscale/integration/scenario.go:336 +0x84
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x7c

Previous write at 0x00c000356030 by goroutine 8:
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser()
      /Users/dongjunna/br/headscale/integration/scenario.go:330 +0x574
  github.com/juanfont/headscale/integration.(*Scenario).CreateHeadscaleEnv()
      /Users/dongjunna/br/headscale/integration/scenario.go:481 +0x218
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable.func1()
      /Users/dongjunna/br/headscale/integration/acl_test.go:274 +0x120
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40

Goroutine 106 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x10c
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser()
      /Users/dongjunna/br/headscale/integration/scenario.go:335 +0x19c
  github.com/juanfont/headscale/integration.(*Scenario).CreateHeadscaleEnv()
      /Users/dongjunna/br/headscale/integration/scenario.go:481 +0x218
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable.func1()
      /Users/dongjunna/br/headscale/integration/acl_test.go:274 +0x120
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40

Goroutine 8 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1742 +0x5e4
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable()
      /Users/dongjunna/br/headscale/integration/acl_test.go:268 +0x1f6c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40
==================
==================
WARNING: DATA RACE
Read at 0x00c0001961d0 by goroutine 106:
  github.com/juanfont/headscale/integration/tsic.New()
      /Users/dongjunna/br/headscale/integration/tsic/tsic.go:195 +0x38c
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser.func1()
      /Users/dongjunna/br/headscale/integration/scenario.go:336 +0xa8
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x7c

Previous write at 0x00c0001961d0 by goroutine 8:
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser()
      /Users/dongjunna/br/headscale/integration/scenario.go:330 +0x4ec
  github.com/juanfont/headscale/integration.(*Scenario).CreateHeadscaleEnv()
      /Users/dongjunna/br/headscale/integration/scenario.go:481 +0x218
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable.func1()
      /Users/dongjunna/br/headscale/integration/acl_test.go:274 +0x120
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40

Goroutine 106 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x10c
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser()
      /Users/dongjunna/br/headscale/integration/scenario.go:335 +0x19c
  github.com/juanfont/headscale/integration.(*Scenario).CreateHeadscaleEnv()
      /Users/dongjunna/br/headscale/integration/scenario.go:481 +0x218
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable.func1()
      /Users/dongjunna/br/headscale/integration/acl_test.go:274 +0x120
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40

Goroutine 8 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1742 +0x5e4
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable()
      /Users/dongjunna/br/headscale/integration/acl_test.go:268 +0x1f6c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40
==================
==================
WARNING: DATA RACE
Read at 0x00c0001961d8 by goroutine 106:
  github.com/juanfont/headscale/integration/tsic.New()
      /Users/dongjunna/br/headscale/integration/tsic/tsic.go:195 +0x38c
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser.func1()
      /Users/dongjunna/br/headscale/integration/scenario.go:336 +0xa8
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x7c

Previous write at 0x00c0001961d8 by goroutine 8:
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser()
      /Users/dongjunna/br/headscale/integration/scenario.go:330 +0x530
  github.com/juanfont/headscale/integration.(*Scenario).CreateHeadscaleEnv()
      /Users/dongjunna/br/headscale/integration/scenario.go:481 +0x218
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable.func1()
      /Users/dongjunna/br/headscale/integration/acl_test.go:274 +0x120
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40

Goroutine 106 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x10c
  github.com/juanfont/headscale/integration.(*Scenario).CreateTailscaleNodesInUser()
      /Users/dongjunna/br/headscale/integration/scenario.go:335 +0x19c
  github.com/juanfont/headscale/integration.(*Scenario).CreateHeadscaleEnv()
      /Users/dongjunna/br/headscale/integration/scenario.go:481 +0x218
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable.func1()
      /Users/dongjunna/br/headscale/integration/acl_test.go:274 +0x120
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40

Goroutine 8 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1742 +0x5e4
  github.com/juanfont/headscale/integration.TestACLHostsInNetMapTable()
      /Users/dongjunna/br/headscale/integration/acl_test.go:268 +0x1f6c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40
```

## Summary by CodeRabbit

- **New Features**
  - Enhanced testing process by adding race detection for both unit and integration tests.
  
- **Bug Fixes**
  - Improved concurrency control in command execution and Tailscale node creation to prevent race conditions, enhancing reliability. 

- **Style**
  - Cleaned up whitespace for better code formatting.

### CODE REVIEW

**Comment by kradalby** [comment]
Good job, looks like there are some more races!

**Comment by kradalby** [comment]
@nadongjun do you have time to have a look at the failing tests?

**Comment by nadongjun** [comment]
@kradalby  Sure, I should be able to complete that by the end of this week.

**Comment by nadongjun** [comment]
@kradalby The timeout issue caused the -race flag to be removed from integration tests. It remains in the Makefile for local testing of race conditions.

**Review by kradalby — APPROVED** [review]

**Pull request merged**
